title: amicum
tagline:
url: "https://ir-g.github.io/amicum"

# Github data

github:
  repo: picoknow/amicum
  branch: gh-pages

# Build settings
markdown:     kramdown
highlighter: rouge
kramdown:
  input: GFM
# permalink:    pretty
paginate: 5
paginate_path: "blog/page-:num/"
sass:
  compressed: true
permalink: /blog/:year-:month-:day/:title
# As according to https://help.github.com/articles/sitemaps-for-github-pages/
gems:
  - jekyll-sitemap

# Set Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
